version: '3'
services: 
    web:
        image: aroopkumargochhayat/shopizer
        ports:
         - "8080:8080"
        links:
         - "db"
    db:
        image: aroopkumargochhayat/mysql
        environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: SALESMANAGER

        ports:
         - "3306:3306"
